### ISSUE TITLE
Instructions to run the project are missing!

### ISSUE THREAD

**Issue by sganesh1975** [thiru15ch/Sadguru#1]
Please provide instructions on how to run the project locally and list all the prerequisites required.

**Comment by thiru15ch** [comment]
Prerequisites:

Python 3.7.3
phpadmin (for my SQL)
flask

**Comment by sganesh1975** [comment]
Assume I don't know anything about python. If I install those and download this project, will it work?

**Comment by thiru15ch** [comment]
Please find the attached file that contains pre-requisites and instructions to run the project

[prerequisites.txt](https://github.com/thiru15ch/Sadguru/files/4750042/prerequisites.txt)

and also updated the same in README.md file
